accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.custom_login, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/<str:username>/', views.profile_details, name='profile'),
    path('profile/update/<str:username>/',
    views.update_profile, name='edit_profile'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.RecipeList, name='recipes'),
    # Create recipe
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    # Recipe Detail
    path('recipe/<str:slug>/', views.recipe_detail, name='recipe_detail'),
    # Edit recipe
    path('edit_recipe/<str:slug>/', views.EditRecipe, name='edit_recipe'),
    # Delete recipe
    path('delete_recipe/<str:slug>/delete/',
         views.delete_recipe, name='delete_recipe'),
    # Likes
    path('recipes/<str:slug>/like/', views.like_recipe, name='like_recipe'),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from blog.views import custom_404
from django.conf.urls import handler404
from django.conf import settings



# project url routes
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),

]
if settings.DEBUG == False:
    urlpatterns += [
    path('404/', custom_404),
]
else:
    handler404 = 'blog.views.custom_404'

accounts/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.conf import settings
from django.contrib.auth import get_user_model


# create a custom user
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

# create user profile


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_picture = CloudinaryField('profile_picture', default='https://res.cloudinary.com/dxtdvo8ix/image/upload/v1699821909/uwmy2pkazv6ukhsknz3m.jpg')
    bio = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
# return the username

    def __str__(self):
        return str(self.user.username)
# check current user

    def check_user(self):
        return self.get.object().user == self.request.user

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser, Profile

# User registration form


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email')
# Login form


class CustomUserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser

# Editing user profile


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)

    class Meta:
        model = Profile
        fields = ['profile_picture', 'bio', 'first_name', 'last_name']

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetView, PasswordResetCompleteView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Profile, CustomUser
from .forms import EditProfileForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib import messages

# Create your views here.

# User registration page view


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Log the user automatically
            login(request, user)
            messages.success(request, 'Registration successful. You are now logged in.')
            # Create user profile
            Profile.objects.create(user=user)
            # Redirect to the homepage
            return redirect('recipes')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/registration/registration.html', {'form': form})

# User login view


def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Welcome, you are now logged in.')
                return redirect('recipes')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/registration/login.html', {'form': form})

# Profile details


@login_required
def profile_details(request, username):
    user = get_object_or_404(CustomUser, username=username)
    user_profile = get_object_or_404(Profile, user=user)
    return render(request, 'accounts/profile/profile.html', {'user_profile': user_profile})

# update profile


@login_required
def update_profile(request, username):
    user = request.user
    user_profile = Profile.objects.get(user=user)

    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            # Accessing form data 
            bio = form.cleaned_data['bio']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            form.save()
            # Update Form Data
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            messages.success(request, "Profile information Updated Successfully.")
            return redirect('profile', username=username)
    else:
        form = EditProfileForm(instance=user_profile)
    form.fields['first_name'].initial = user.first_name
    form.fields['last_name'].initial = user.last_name
    profile_pic = user_profile.profile_picture.url
    return render(request, 'accounts/profile/update_profile.html', {'form': form, 'profile_pic': profile_pic})

accounts/templates/accounts/profile/profile.html
{% extends "blog/base.html" %}  {% load static %} 

{% block extracss %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/css/profile.css' %}"/>

{% endblock extracss %}

{% block content %}

    <div class="container mt-5">
    <div class="row justify-content-center">
        
        <div class="col-md-8">
            <!-- User Details Card -->
            <div class="card mb-4  border-top-0">
                <div class="card card-header">
                    <h2 class="mx-auto text-center mb-3">  Profile Details  </h2>
                </div>
                <div class="card-body">
                    <p class="p1">
                        <strong><em><u><h5>USER DETAILS</h5></u></em></strong>
                    </p>
                    <div class="row details-row">
                        <div class="col-12 col-md-6">
                            <div class="profile-image text-center">
                                <img class="img-fluid rounded-3 m-2" src="{{user_profile.profile_picture.url}}" alt="Profile">
                            </div>
                            
                        </div>
                        <div class="col-12 col-md-5 ms-3 my-2 details">
                            <div class="name">
                                <p><strong>Name:</strong> {{ user_profile.user.first_name }} {{ user_profile.user.last_name }}</p>
                            </div>
                            <div class="uname">
                                <p><strong>Username:</strong> {{ user_profile.user.username }}</p>
                            </div>
                            <div class="bio">
                                <p><strong>User Bio:</strong> {{ user_profile.bio }}</p>
                            </div>
                        </div>
                        <h4 class="mx-5 text-center mx-auto text-info">Actions</h4>
                        <div class="edit-profile btn mt-3 col-4 d-flex justify-content-center mx-auto px-auto">
                            <a class="btn-info border-dark px-3" href="{% url 'edit_profile' username=user.username %}"><i class="fa-sharp fa-solid fa-user-pen"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- User History Card -->
            <div class="card my-2">
                <div class="card-body">
                    <h5 class="history"><strong> <u>User History</u></strong></h5>
                    <div class="member-p">
                        <p>You have been our Member since {{ user_profile.created_on }}</p>
                    </div>
                    <div class="update">
                        <p>You last updated your Profile details on {{ user_profile.updated_on }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock content %}

accounts/templates/accounts/profile/update_profile.html
{% extends "blog/base.html" %} {% load static %} {% load recipe_filters %} 

{% block extracss %}

<link rel="stylesheet" href="{% static 'blog/css/update_profile.css' %}" />

{% endblock extracss %} 

{% block content %}
<div class="container my-3">
  <div class="col prof-update mx-2">
    <div class="card card-header">
      <h2 class="text-center">Update Your Profile</h2>
    </div>
    <div class="card-body p-2">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row align-items-center mb-4">
          <!-- Profile Picture Field -->
          <div class="col-md-6 text-center">
            <label for="id_profile_picture" class="form-label"
              >Profile Picture</label
            >
            <div class="d-flex flex-column align-items-center">
              <img
                src="{{ profile_pic }}"
                alt="Current Profile Picture"
                class="img-fluid rounded-circle mb-2"
                style="height: 150px"
              />
              <div class="change">
                <input
                  type="file"
                  name="profile_picture"
                  id="id_profile_picture"
                  class="form-control"
                />
              </div>
            </div>
          </div>

          <!-- Bio Field -->
          <div class="col-md-6 align-items-start">
            <label for="id_bio" class="form-label">Bio</label>
            {{ form.bio }}
          </div>
        </div>

        <hr>

        <!-- First Name and Last Name Fields -->
        <div class="row mb-3">
          <h3 class="mb-4"><u>User Name</u></h3>
          
          <div class="col-md-6">
            <label for="id_first_name" class="form-label">First Name</label>
            {{ form.first_name }}
            {{ form.first_name.errors }}
          </div>
          <div class="col-md-6">
            <label for="id_last_name" class="form-label">Last Name</label>
            {{ form.last_name }}
            {{ form.last_name.errors }}
          </div>
        </div>

        <div class="row mt-5 align-start">

          <div class="save col-md-6 col-sm-6 col-xs-6 col-6">
            <button type="submit" class="btn btn-primary my-2 me-3  m-auto no-wrap">Save</button>
          </div>
          

          <div class="cancel col-md-6 col-sm-6 col-xs-6 col-6">
            <a class="btn btn-secondary  my-2 m-auto" href="{% url 'profile' username=user.username %}">Cancel</a>
          </div>
          
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}